
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import 'react-notifications-component/dist/theme.css'
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import Header from "@/CustomComponents/Layout/Header";
import { hydrateRoot } from "react-dom/client";
import Footer from "@/CustomComponents/Layout/Footer";
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import "@fortawesome/fontawesome-free/css/all.min.css"
import ReduxProvider from "@/lib/Reducers/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import 'react-toastify/dist/ReactToastify.css';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
      
      <MantineProvider>
      <Header />
        {children}
        <Footer />
        
        </MantineProvider>
   
        </body>
      </ReduxProvider>
      
    </html>
   
  );
}
