import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css"
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import "@fortawesome/fontawesome-free/css/all.min.css"
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import ReduxProvider from "@/lib/Reducers/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <ColorSchemeScript />
    </head>
    <ReduxProvider>
    <body className={inter.className}>
    
    <MantineProvider>

      {children}
      
      
      </MantineProvider>
 
      </body>
      </ReduxProvider>
  </html>
   
  );
}
