import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import Header from "@/CustomComponents/Layout/Header";
import { hydrateRoot } from "react-dom/client";
import Footer from "@/CustomComponents/Layout/Footer";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
      <Header />
      <MantineProvider>{children}</MantineProvider>
      <Footer />
        </body>
    </html>
   
  );
}
